### ISSUE TITLE
Crash starting ExportIt

### ISSUE THREAD

**Issue by elfren** [WilkoV/Fusion360_ExportIt#21]
ExportIt dialog did not fully populate:
![ExportError3](https://user-images.githubusercontent.com/9331987/93654915-43427300-f9d5-11ea-83c5-da1ebcc91138.JPG)

[BoneBox v13.zip](https://github.com/WilkoV/Fusion360_ExportIt/files/5248853/BoneBox.v13.zip)

**Comment by elfren** [comment]
Error text:
---------------------------
Fusion 360
---------------------------
Input changed event failed: Traceback (most recent call last):
  File "C:/Users/Elf/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/AddIns/Fusion360_ExportIt-main\apper\apper\Fusion360CommandBase.py", line 419, in notify
    self.cmd_object_.on_input_changed(command_, command_inputs, changed_input, input_values)
  File "C:/Users/Elf/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/AddIns/Fusion360_ExportIt-main\commands\ExportItExportDesignCommand.py", line 1087, in on_input_changed
    validateConfiguration(inputs)
  File "C:/Users/Elf/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/AddIns/Fusion360_ExportIt-main\commands\ExportItExportDesignCommand.py", line 254, in validateConfiguration
    showHideCustomStlSettings(inputs)
  File "C:/Users/Elf/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/AddIns/Fusion360_ExportIt-main\commands\ExportItExportDesignCommand.py", line 197, in showHideCustomStlSettings
    hideUiElement(inputs, CONF_STL_SURFACE_DEVIATION_KEY)
  File "C:/Users/Elf/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/AddIns/Fusion360_ExportIt-main\commands\UiHelper.py", line 215, in hideUiElement
    element.isVisible = False
AttributeError: 'NoneType' object has no attribute 'isVisible'

---------------------------
OK   
---------------------------

**Comment by WilkoV** [comment]
Broken because of logging code. That's not nice. If fixed the problem and pushed it to the branch 0.8.0. You can either switch to the branch or you can use one of the attached files. I merge it to to main later.
Because of this issue I found another one: You don't get warnings if your file contains meshes. I never use them so I missed that. I'll try to fix it next.

[ExportIt.zip](https://github.com/WilkoV/Fusion360_ExportIt/files/5249911/ExportIt.zip)
[ExportIt.tar.gz](https://github.com/WilkoV/Fusion360_ExportIt/files/5249912/ExportIt.tar.gz)

**Comment by elfren** [comment]
The fix works.
